/**
 * Value Metrics Service
 * 
 * Tracks and calculates ROI metrics for users:
 * - AI assistant time saved
 * - Compliance check cost savings
 * - Total value delivered
 * - Usage statistics
 */

import { Service } from '@liquidmetal-ai/raindrop-framework';
// import { Env } from './raindrop.gen';  // Will be generated by raindrop build
import { Kysely } from 'kysely';
import { D1Dialect } from '../common/kysely-d1';
import { DB } from '../db/auditguard-db/types';

// Temporary Env interface until raindrop.gen is generated
interface Env {
  AUDITGUARD_DB: any;
  AUTH_SERVICE: {
    verifySession(sessionId: string): Promise<{ userId: string }>;
  };
}

interface ValueMetrics {
  timeSaved: {
    hours: number;
    description: string;
  };
  costSavings: {
    amount: number; // in cents
    currency: string;
    description: string;
  };
  usageStats: {
    aiMessagesCount: number;
    complianceChecksCount: number;
    documentsProcessed: number;
    issuesIdentified: number;
  };
  roi: {
    value_delivered: number; // in cents
    cost_paid: number; // in cents
    roi_multiple: number;
  };
}

export default class extends Service<Env> {
  private getDb(): Kysely<DB> {
    return new Kysely<DB>({
      dialect: new D1Dialect({ database: this.env.AUDITGUARD_DB }),
    });
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;

    try {
      // Get workspace value metrics
      if (path.match(/^\/workspaces\/[^/]+\/value-metrics$/)) {
        const workspaceId = path.split('/')[2];
        
        // Verify session
        const sessionId = request.headers.get('cookie')?.match(/session=([^;]+)/)?.[1];
        if (!sessionId) {
          return Response.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const session = await this.env.AUTH_SERVICE.verifySession(sessionId);
        const db = this.getDb();

        // Verify workspace access
        const membership = await db
          .selectFrom('workspace_members')
          .select('role')
          .where('workspace_id', '=', workspaceId)
          .where('user_id', '=', session.userId)
          .executeTakeFirst();

        if (!membership) {
          return Response.json({ error: 'Access denied' }, { status: 403 });
        }

        const metrics = await this.calculateValueMetrics(db, workspaceId);
        
        return Response.json(metrics);
      }

      return Response.json({ error: 'Not found' }, { status: 404 });
    } catch (error) {
      console.error('Value Metrics Service error:', error);
      return Response.json(
        { error: 'Internal server error' },
        { status: 500 }
      );
    }
  }

  async calculateValueMetrics(
    db: Kysely<DB>,
    workspaceId: string
  ): Promise<ValueMetrics> {
    // Calculate AI assistant time saved
    // Assumption: Each AI message saves 15 minutes of manual research/writing
    const aiMessageCount = await db
      .selectFrom('conversation_messages')
      .select(({ fn }) => fn.countAll().as('count'))
      .innerJoin('conversation_sessions', 'conversation_messages.session_id', 'conversation_sessions.id')
      .where('conversation_sessions.workspace_id', '=', workspaceId)
      .where('conversation_messages.role', '=', 'assistant') // Only count AI responses
      .executeTakeFirst();

    const aiMessages = Number(aiMessageCount?.count || 0);
    const minutesSavedPerMessage = 15;
    const aiTimeSavedMinutes = aiMessages * minutesSavedPerMessage;
    const aiTimeSavedHours = aiTimeSavedMinutes / 60;

    // Calculate compliance check cost savings
    // Industry benchmark: Manual compliance audit costs $100-500 per check
    // We use $150 as average
    const complianceCheckCount = await db
      .selectFrom('compliance_checks')
      .select(({ fn }) => fn.countAll().as('count'))
      .where('workspace_id', '=', workspaceId)
      .where('status', 'in', ['completed', 'passed'])
      .executeTakeFirst();

    const complianceChecks = Number(complianceCheckCount?.count || 0);
    const costPerManualCheck = 15000; // $150 in cents
    const complianceCostSavings = complianceChecks * costPerManualCheck;

    // Calculate document processing time saved
    // Assumption: Manual document review takes 30 minutes per document
    const documentCount = await db
      .selectFrom('documents')
      .select(({ fn }) => fn.countAll().as('count'))
      .where('workspace_id', '=', workspaceId)
      .executeTakeFirst();

    const documents = Number(documentCount?.count || 0);
    const minutesSavedPerDocument = 30;
    const documentTimeSavedMinutes = documents * minutesSavedPerDocument;
    const documentTimeSavedHours = documentTimeSavedMinutes / 60;

    // Total time saved
    const totalTimeSavedHours = aiTimeSavedHours + documentTimeSavedHours;

    // Calculate cost savings from time saved
    // Assumption: Compliance professional hourly rate = $75/hour
    const hourlyRate = 7500; // $75 in cents
    const timeSavingsCost = Math.round(totalTimeSavedHours * hourlyRate);

    // Total cost savings
    const totalCostSavings = complianceCostSavings + timeSavingsCost;

    // Get issues identified
    const issuesCount = await db
      .selectFrom('compliance_issues')
      .innerJoin('compliance_checks', 'compliance_issues.check_id', 'compliance_checks.id')
      .select(({ fn }) => fn.countAll().as('count'))
      .where('compliance_checks.workspace_id', '=', workspaceId)
      .executeTakeFirst();

    const issues = Number(issuesCount?.count || 0);

    // Calculate ROI
    // Get workspace's current subscription cost
    const workspace = await db
      .selectFrom('workspaces')
      .select(['organization_id'])
      .where('id', '=', workspaceId)
      .executeTakeFirst();

    let costPaid = 0; // Free plan
    
    if (workspace?.organization_id) {
      const subscription = await db
        .selectFrom('subscriptions')
        .innerJoin('subscription_plans', 'subscriptions.plan_id', 'subscription_plans.id')
        .select(['subscription_plans.price_monthly'])
        .where('subscriptions.organization_id', '=', workspace.organization_id)
        .where('subscriptions.status', 'in', ['active', 'trialing'])
        .executeTakeFirst();

      if (subscription) {
        costPaid = subscription.price_monthly;
      }
    }

    const valueDelivered = totalCostSavings;
    const roiMultiple = costPaid > 0 ? valueDelivered / costPaid : 0;

    return {
      timeSaved: {
        hours: Math.round(totalTimeSavedHours * 10) / 10, // Round to 1 decimal
        description: `${Math.round(aiTimeSavedHours)} hours from AI assistant + ${Math.round(documentTimeSavedHours)} hours from document automation`,
      },
      costSavings: {
        amount: totalCostSavings,
        currency: 'USD',
        description: `$${(complianceCostSavings / 100).toFixed(0)} from compliance automation + $${(timeSavingsCost / 100).toFixed(0)} from time savings`,
      },
      usageStats: {
        aiMessagesCount: aiMessages,
        complianceChecksCount: complianceChecks,
        documentsProcessed: documents,
        issuesIdentified: issues,
      },
      roi: {
        value_delivered: valueDelivered,
        cost_paid: costPaid,
        roi_multiple: Math.round(roiMultiple * 10) / 10, // Round to 1 decimal
      },
    };
  }
}
