#!/bin/bash

echo "🌐 WSL Network Access Guide"
echo "==========================="
echo ""

# Get WSL IP
WSL_IP=$(ip addr show eth0 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)

if [ -z "$WSL_IP" ]; then
    echo "❌ Could not determine WSL IP address"
    exit 1
fi

echo "✅ Your WSL IP address: $WSL_IP"
echo ""
echo "📋 Instructions to access from Windows browser:"
echo ""
echo "1️⃣  Make sure your dev server is running in WSL:"
echo "   cd /home/patrick/championship/auditguard-ui"
echo "   npm run dev"
echo ""
echo "2️⃣  Open a Windows browser (Chrome, Edge, Firefox on Windows, NOT in WSL)"
echo ""
echo "3️⃣  Try these URLs (in order):"
echo ""
echo "   Option A - Localhost (easiest):"
echo "   https://localhost:3000"
echo ""
echo "   Option B - WSL IP:"
echo "   https://$WSL_IP:3000"
echo ""
echo "4️⃣  When you see 'Your connection is not private':"
echo "   • Click 'Advanced'"
echo "   • Click 'Proceed to localhost (unsafe)' or 'Proceed to $WSL_IP (unsafe)'"
echo ""
echo "5️⃣  Test Voice Mode:"
echo "   • Navigate to AI Assistant page"
echo "   • Click the gradient Voice Mode button (top right)"
echo "   • Click 'Start Recording'"
echo "   • Grant microphone permission"
echo "   • ✅ Should work!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 Troubleshooting:"
echo ""
echo "If localhost:3000 doesn't work:"
echo "  1. Check Windows Firewall isn't blocking WSL"
echo "  2. Try the WSL IP directly: https://$WSL_IP:3000"
echo ""
echo "If WSL IP doesn't work:"
echo "  1. Check WSL2 networking: wsl --list --verbose (should show Version 2)"
echo "  2. Restart WSL: wsl --shutdown, then restart"
echo ""
echo "Still not working?"
echo "  Deploy to production and test there:"
echo "    cd /home/patrick/championship/auditguard-v2"
echo "    raindrop build deploy"
echo "    Visit: https://auditguardx.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
